Repository FrozenAssassine/TextControlBox-UWP, pull requests merged in 2023-05, with the labels that each got.

#385 Fix: Move line scroll into view
  TextControlBox/TextControlBox.xaml.cs
Labels: bug

#384 This properly adds shift + leftclick to select text
  TextControlBox/TextControlBox.xaml.cs
Labels: enhancement

#381 Added CSV, LaTex, TOML, Markdown
  TextControlBox/Languages/Languages.cs
Labels: enhancement, Syntaxhighlighting
